### PR TITLE
Implement a themed app icon

### PR DESCRIPTION
**Pull request by psbankar**
## Summary

Implement a themed app icon according to Android 13 user eperience
https://developer.android.com/about/versions/13/features#themed-app-icons

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @psbankar, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#2371).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by dshokouhi** [comment]
I think we need a new icon for this right?

**Comment by psbankar** [comment]
Yes, the current icon works perfectly but the weird issue is this themed icons feature is working for many apps by default without any code changes on Android 12 whereas, for Home Assistant, it's not working on Android 12 even with code changes. On adding the monochrome tag, the themed icon is working on Android Tiramisu preview.


Screenshot

**Comment by psbankar** [comment]
@dshokouhi let me know if should reopen the PR for review or discard it.

**Comment by dshokouhi** [comment]
> Yes, the current icon works perfectly but the weird issue is this themed icons feature is working for many apps by default without any code changes on Android 12 whereas, for Home Assistant, it's not working on Android 12 even with code changes. On adding the monochrome tag, the themed icon is working on Android Tiramisu preview.

I thought that this is expected behavior in android 12 as its only been opened up to Google apps but I could be mistaken. I think android 13 was supposed to open it up so that sounds about right to me.



> let me know if should reopen the PR for review or discard it.

I think we can leave it open for now to get an opinion from other reviewers,

**Pull request merged**
