### PR TITLE
Remove call number sensor due to policy changes at Google.

### PR DESCRIPTION
**Pull request by JBassett**

### CODE REVIEW

**Comment by dshokouhi** [comment]
should we also remove the strings for the sensor?

**Comment by sep-don-barrett** [comment]
Not everyone installs through the Google Play Store and its increasingly arbitrary policy requirements.  Might I suggest leaving the code in place and not building it for Play Store releases? Some of us like this capability.

**Comment by dshokouhi** [comment]
@sep-don-barrett you can use the new Last Notification sensor to do the exact same thing.  This call number sensor was a beta feature and not released yet.   Last Notification is also a beta feature and if you use the phone app in its allow list you can get the same data.

**Comment by JBassett** [comment]
It could be moved to the minimal build of the application if desired.

**Pull request merged**
