### PR TITLE
Initial commit of failed connection attempt notification

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Fixes: #1033 

This PR will keep track of failed connection attempts.  As of now I have chosen `5` as the maximum before pushing the notification however we can change this to a higher number.

For just about every call we make we either reset the count or add to the count for failed connection attempts.

The notification is persistent and has a chronometer to help the user understand how long its been since the app was able to reach HA.

Once a call is successful the notification will be removed without any intervention by the user.

I wanted to submit this now to get feedback from beta testers to find out how the functionality is and what improvements we need to make.

We will also be using a different notification channel so users can customize it to their liking.

I tried to test as much as I could by updating widgets, triggering sensor updates, launching HA all while my dev server was offline.  Testing was good on all fronts and have made adjustments to when the calls actually need to be made.  Sensor Receiver for example only makes the assumption if we are unable to update the sensor because we first register then update so only makes sense to make 1 call there.

## Screenshots

image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Review by JBassett — CHANGES_REQUESTED** [review]
If we are going to do something like this we need a better cross cutting location to do it.  I don't think it's a good idea to have the create / remove scattered across all the service calls like that.  It should really be a filter on all those calls instead.

**Comment by dshokouhi** [comment]
How do you recommend we go about getting `context` in the `IntegrationRepositoryImpl.kt` file? Maybe its my misunderstanding of dagger but I didn't see how we can inject context like we can in other locations.  That would allow us to keep all the logic in the same file so we can post a notification.  I'd love for it to be as part of the retrofit but I didn't see a way to do that there either.

**Comment by dshokouhi** [comment]
I think the only way to do this properly is to pass in `context` from all the calls that are made to HA so we can keep it all in one place `IntegrationRepositoryImpl.kt`.  Would that make sense for this or is there a cleaner way to go about it?

**Comment by dshokouhi** [comment]
Made some updates to make everything more centralized.  WebView and the entity state widget are the only places I was unable to change the logic.  Webview needs its own logic for this as we rely on frontend messages as well as the cannot connect pop-up.  For the entity state widget its the only widget that doesn't have a service call and checking for null values won't really work here compared to the rest.  I can remove it if we think it should be removed but majority of logic is now kept in the integration repository.  Only passing in context so we can post the notification correctly.

**Comment by dshokouhi** [comment]
Did some thorough testing and discovered sometimes the connection count gets reset and fails again causing a new notification that doesn't get cleared later on when connection is restored.  Will need to find out where that bug is but will keep this open to see if this is a desired path anyways.

**Comment by dshokouhi** [comment]
Looks like I can reproduce by clearing app from recent apps screen so marking as draft again

**Comment by dshokouhi** [comment]
Closing until the app has proper websocket support, as of now the current implementation is just not ideal and touches on too many files.

**Pull request closed without merging**
