### PR TITLE
Fix typo in readme file

### PR DESCRIPTION
**Pull request by joostlek**
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @joostlek, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#2132).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by joostlek** [comment]
After following the readme I found a few things that went different. Should I include them into this PR and make this a readme improvement PR or should I create a new PR for that

**Comment by dshokouhi** [comment]
> After following the readme I found a few things that went different. Should I include them into this PR and make this a readme improvement PR or should I create a new PR for that

Feel free to include them in here 🙂

**Comment by joostlek** [comment]
> > After following the readme I found a few things that went different. Should I include them into this PR and make this a readme improvement PR or should I create a new PR for that
> 
> Feel free to include them in here 🙂

Updated! When I generated my keystore, I got an error which said it ignored my alias password because it did not support it. Can you test if you have this too? If that happens it will default to the keystore password. I can imagine having a hard time figuring out why a build would fail.

**Comment by joostlek** [comment]
> > Updated! When I generated my keystore, I got an error which said it ignored my alias password because it did not support it. Can you test if you have this too? If that happens it will default to the keystore password. I can imagine having a hard time figuring out why a build would fail.
> 
> hmm I do not have a keystore file in those location and I do not have any issues with builds running.

What OS are you using?

**Comment by dshokouhi** [comment]
i am on windows 10

**Comment by joostlek** [comment]
> i am on windows 10

Do you have the KEYSTORE_PATH env set to something? Apparently it defaults to the release_keystore.keystore.

`signingConfigs {
        create("release") {
            storeFile = file(System.getenv("KEYSTORE_PATH") ?: "release_keystore.keystore")
            storePassword = System.getenv("KEYSTORE_PASSWORD") ?: ""
            keyAlias = System.getenv("KEYSTORE_ALIAS") ?: ""
            keyPassword = System.getenv("KEYSTORE_ALIAS_PASSWORD") ?: ""
            enableV1Signing = true
            enableV2Signing = true
        }
    }`

**Comment by dshokouhi** [comment]
> > i am on windows 10
> 
> Do you have the KEYSTORE_PATH env set to something? Apparently it defaults to the release_keystore.keystore.
> 
> ```
>         create("release") {
>             storeFile = file(System.getenv("KEYSTORE_PATH") ?: "release_keystore.keystore")
>             storePassword = System.getenv("KEYSTORE_PASSWORD") ?: ""
>             keyAlias = System.getenv("KEYSTORE_ALIAS") ?: ""
>             keyPassword = System.getenv("KEYSTORE_ALIAS_PASSWORD") ?: ""
>             enableV1Signing = true
>             enableV2Signing = true
>         }
>     }
> ```

ok I only get this issue when I build for `release` personally I never have a need for that....When you look at the left side window you will see "Build Variants" click on that and change it to one of the debug releases and it will work.  I never used release since I dont use them for development.

image

**Comment by joostlek** [comment]
Does `gradlew build` default to the release variant? And if we only build the debug builds, why bother making a keystore?

**Comment by dshokouhi** [comment]
> Does `gradlew build` default to the release variant?

looks like it does



> And if we only build the debug builds, why bother making a keystore?

I think its for the forks?

**Comment by joostlek** [comment]
> > Does `gradlew build` default to the release variant?
> 
> looks like it does
> 
> > And if we only build the debug builds, why bother making a keystore?
> 
> I think its for the forks?

Doesn't that mean we can remove that step from the setup. (Or place it under a "If you want to fork and sign it"). And change the gradle command to one that just builds the debug ones.

**Comment by dshokouhi** [comment]
Good points :) lets wait for another reviewer so we can make an appropriate decision here

**Comment by JBassett** [comment]
> Does `gradlew build` default to the release variant?

It actually builds and tests all variants



> `gradlew assembleDebug` only builds the debug applications, so it doesn't require a Keystore. So it would be that or having people specify the path to their keystore (which they probably won't use)

Breaking down the steps further probably makes sense.  Most people contributing only need debug builds.  I would break this into two sections I guess.  Development, what most people are going to do.  Then a preparing for publishing, which we can mention that is only for those who publish the application.

**Comment by joostlek** [comment]
When generating a signed APK, should we just say follow the intellij tutorial or also include the gradlew build part with the environment variables?

**Review by JBassett — APPROVED** [review]

**Review by dshokouhi — APPROVED** [review]
Thank you for cleaning this up!

**Pull request merged**
