### PR TITLE
Add a battery power sensor

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Fixes: #2796 by adding a new sensor which takes in the current and voltage and sends the wattage back to HA with current and voltage as the attributes.

## Screenshots

Discharging:
image

Charging via USB;
image

Fast charging:
image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#793

### CODE REVIEW

**Comment by jpelgrom** [comment]
Is "Charging Wattage" the right name for this sensor? It also reports values when not charging.

I wonder how accurate this is - I'm getting 3-5W less than a power plug with monitoring shows.

**Comment by dshokouhi** [comment]
> Is "Charging Wattage" the right name for this sensor?

it was the best name I could come up with unless we want to call it battery wattage?



> It also reports values when not charging.

negative values mean the device is not charging, positive values is when its charging. I decided against setting it to 0 as it can probably indicate heavier drain? the API is still returning values and it seems odd to set the state to 0 or something else when `current` is negative :) I even doubted myself and googled if negative wattage is expected 😂 



> I wonder how accurate this is - I'm getting 3-5W less than a power plug with monitoring shows.

I have no idea but if you notice the value changes a lot over a short period of time so it may not be meaningful if it updates every 15 minutes. The other variables in AOSP are inaccessible to the app so I had to work with what I could get lol.

**Comment by jpelgrom** [comment]
> > Is "Charging Wattage" the right name for this sensor?
> 
> it was the best name I could come up with unless we want to call it battery wattage?

Watt is the unit for electric power, so maybe "battery power"? A plug which provides an entity that shows watts also shows up as [device name] power in HA.

> negative values mean the device is not charging, positive values is when its charging. I decided against setting it to 0 as it can probably indicate heavier drain? the API is still returning values and it seems odd to set the state to 0 or something else when `current` is negative :) I even doubted myself and googled if negative wattage is expected 😂

Maybe the icon should reflect that? `mdi:battery-plus` and `mdi:battery-minus` instead of a generic battery or charging battery.

> I have no idea but if you notice the value changes a lot over a short period of time so it may not be meaningful if it updates every 15 minutes. The other variables in AOSP are inaccessible to the app so I had to work with what I could get lol.

I didn't notice that, probably a good idea to mention it in the sensor description. I'll keep this version installed to see how it changes over time and whether the sensor could be useful or not.

**Comment by dshokouhi** [comment]
> Watt is the unit for electric power, so maybe "battery power"? A plug which provides an entity that shows watts also shows up as [device name] power in HA.

battery power sounds much better 😄 

> Maybe the icon should reflect that? `mdi:battery-plus` and `mdi:battery-minus` instead of a generic battery or charging battery.
> 
> >

Yup that is better icon usage, thank you



> I didn't notice that, probably a good idea to mention it in the sensor description. I'll keep this version installed to see how it changes over time and whether the sensor could be useful or not.

ok will update the description to mention  to get the most of the sensor its best paired with "Fast while charging" frequency updates

**Review by JBassett — APPROVED** [review]

**Pull request merged**
