### PR TITLE
Temporarily disable health connect to satisfy play console

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Our releases are stuck in a weird place given health connect approval is taking longer than anticipated and the required SDK bump deadline has passed.

For now lets temporarily comment out the code for permissions and health connect sensors while we satisfy the SDK requirements. Once completed and reviewed we should revert this change and try again for approval.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

more details: https://github.com/home-assistant/android/pull/4452#issuecomment-2321697048

### CODE REVIEW

**Review by jpelgrom — APPROVED** [review]

**Comment by jpelgrom** [comment]
Let's unblock this :)

**Comment by mapsindustrial** [comment]
Guys, I am very very interested in being able to try the great work you have done, is there any possibility of trying the apk?

**Comment by dshokouhi** [comment]
> Guys, I am very very interested in being able to try the great work you have done, is there any possibility of trying the apk?

just give some patience, we are waiting on the current production release to be approved by Google so we can move forward with #4663 so we can hopefully apply for the approval so the features can work.

**Comment by mapsindustrial** [comment]
Do you know an approximate date? Will they release the apk in the Google Pay Store?

**Comment by mapsindustrial** [comment]
Great, that's great news. I'm crossing my fingers to have a date soon. 

Thank you so much!

**Pull request merged**
