### PR TITLE
Add wear sensors

### PR DESCRIPTION
**Pull request by Kisty**
## Summary

Adding wearOS device sensors. Starting with battery. This is a work in progress.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

#1613

### CODE REVIEW

**Comment by dshokouhi** [comment]
Glad that we are getting work started on wear sensors, wonder how many we will get to 😄 Look forward to testing things out once ready.

**Comment by Kisty** [comment]
@JBassett Hey! Sorry I've been quiet. Been battling some viruses in the household but out on the other side. Has this already been implemented? If not why close the PR?

**Comment by JBassett** [comment]
@Kisty Glad you are on the other side of it.  If you are still working on the PR feel free to reopen, I closed because the build had been failed for a while with no activity.

**Comment by Kisty** [comment]
@JBassett have fixed the build and pushed, but the PR is closed. Will it build while it's closed? I can't reopen the PR.

**Comment by JBassett** [comment]
If you force push the branch it appears you need to open a new PR.

**Comment by Kisty** [comment]
OK, that's fair. Will I lose the hacktoberfest thing if I reopen?

**Comment by dshokouhi** [comment]
@Kisty check your hacktoberfest profile it should still show up. The PR never received the `invalid` label which is what I believe they look for.

**Pull request closed without merging**
