### PR TITLE
Update sensors when BLE transmitter turned on and off

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Fixes: #3384 by updating sensors anytime the command is processed 

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by jpelgrom** [comment]
Is there a particular reason for not adding this to `enableDisableBLETransmitter` instead, to match how beacon monitor commands are processed? That function already handles starting/stopping on change and updating the state.

**Comment by dshokouhi** [comment]
> Is there a particular reason for not adding this to `enableDisableBLETransmitter` instead, to match how beacon monitor commands are processed? That function already handles starting/stopping on change and updating the state.

Beacon Monitor only allows for enable and disable, the BLE transmitter also allows changing other sensor settings which get reflected in the attributes so we also want to update that.

**Comment by jpelgrom** [comment]
OK should the starting/stopping be removed from `enableDisableBLETransmitter` then as it's also handled in the sensor update? Less duplicate code.

**Comment by dshokouhi** [comment]
> OK should the starting/stopping be removed from `enableDisableBLETransmitter` then as it's also handled in the sensor update? Less duplicate code.

Good call, just tested removing that code and it seems to work as intended

**Review by jpelgrom — APPROVED** [review]
Tested and it appears to be working correctly

**Review by JBassett — APPROVED** [review]

**Pull request merged**
