### PR TITLE
Initial commit of notification support on Wear OS

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

This PR adds initial support for `message` and `title` only as there is a lot to move and test. The goal here is to get notifications sending to the watch directly as an MVP. 

I tried to keep the changes minimal here but I am sure there will be room for improvements.

```
message: Message
title: Title
```

## Screenshots

image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#884

## Any other notes

More than likely the next PR after this will be to add device commands for the BLE sensors as those are probably going to be the most important here :)

Its important to note that this will not be testable using the debug APKs as they are from FCM. I have not given too much thought about the warning pop-up we do but given all Wear OS devices will have FCM I don't think it will be too much of a concern. If FCM does not work then functionality will default to existing behavior which is a no-op.

### CODE REVIEW

**Comment by jpelgrom** [comment]
I'm not sold on dumping everything in a related package as functions + tons of imports. Especially for the constants putting them in an object (`NotificationData`?) would clean up the usage. Maybe I'm thinking too much in Java but when there's comments above a set of constants that suggests to me that they should be organized as such.

While it is unlikely that Wear will ever get another entrypoint for notifications, why put all the code in `FirebaseMessagingService`? Splitting it up to keep the Firebase code separate from the notification handling code results in a smaller file, making it easier to read and compare with the main app.

**Comment by dshokouhi** [comment]
> Especially for the constants putting them in an object (`NotificationData`?) would clean up the usage. Maybe I'm thinking too much in Java but when there's comments above a set of constants that suggests to me that they should be organized as such.

This makes sense to me I will move it all to an object to reduce the amount of imports



> While it is unlikely that Wear will ever get another entrypoint for notifications, why put all the code in `FirebaseMessagingService`?

I just called it `FirebaseMessagingService` as most (not all) of the code applies to Wear OS as we need to handle new tokens etc... Also not all is supported here so I kept it all in the same file. We can rename it if we want to make it more generic?

> Splitting it up to keep the Firebase code separate from the notification handling code results in a smaller file, making it easier to read and compare with the main app.

Not sure I follow here? The phone and Wear app will need to differentiate between what they can and can't support like video handling and various device commands that are phone specific. I thought the split I did would be sufficient as phone and watch will have separate logic they need to maintain. We can share some things still.

**Comment by jpelgrom** [comment]
> I just called it `FirebaseMessagingService` as most (not all) of the code applies to Wear OS as we need to handle new tokens etc... Also not all is supported here so I kept it all in the same file. We can rename it if we want to make it more generic?
>
> (...)
>
> Not sure I follow here? The phone and Wear app will need to differentiate between what they can and can't support like video handling and various device commands that are phone specific.

Nothing wrong with the name. Obviously the Firebase-specific code needs to live somewhere. Trying to explain it differently: why not introduce a `MessagingManager`-like class for the `wear` module as well that deals with the functional stuff (notifications)? `FirebaseMessagingService` can do the housekeeping for receiving push data and refreshing tokens. By doing that it better mimics what is done in the main app, which makes it easy to compare code and introduce features in the same way.

> I thought the split I did would be sufficient as phone and watch will have separate logic they need to maintain. We can share some things still.

Yes the current approach for that is fine :)

**Comment by dshokouhi** [comment]
> Trying to explain it differently: why not introduce a `MessagingManager`-like class for the `wear` module as well that deals with the functional stuff (notifications)? `FirebaseMessagingService` can do the housekeeping for receiving push data and refreshing tokens. By doing that it better mimics what is done in the main app, which makes it easy to compare code and introduce features in the same way.

Thanks thats more clear now!

**Comment by jpelgrom** [comment]
Minor issue, building initially failed for me with:

```
Execution failed for task ':wear:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  \home-assistant-android\wear\src\debug\google-services.json
  \home-assistant-android\wear\src\google-services.json
  \home-assistant-android\wear\google-services.json
```

In my opinion the README should be updated to mention this, it currently only refers to the main `app` module.

The app is also [always sending `"push_websocket_channel": true` in the registration JSON](https://github.com/home-assistant/android/blob/5cd74c0179f13b617de517273ec860215a8259ba/common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt#L762), that should probably be changed for the Wear app.

**Comment by jpelgrom** [comment]
Looks like push notifications are working 🥳 Tested an upgrade as well and it is handled automatically during re-registration.

A screenshot of a notification from the Home Assistant Wear app, titled "Hello!" and with the message "Via the cloud ☁️"

**Comment by dshokouhi** [comment]
Awesome next commit I will update the readme and also for device registration will set it to `false` from wear OS as the phone app is always going to be `true` there. Have code changes ready just want to test before committing.

**Comment by jpelgrom** [comment]
The latest Firebase BoM is 31.1.1, I don't see a reason to use an older version.

Other code looks good to start building notification support on to me!

**Comment by dshokouhi** [comment]
> The latest Firebase BoM is 31.1.1, I don't see a reason to use an older version.

ah I copied and pasted the main app version, let me bump both of them :) 

Surprised android studio doesn't highlight it like the others 🤔

**Review by jpelgrom — APPROVED** [review]
I think this is a good start, let's see how it scales once more notification features are supported

**Review by JBassett — APPROVED** [review]

**Pull request merged**
