### PR TITLE
use androidx.core.view.isVisible

### PR DESCRIPTION
**Pull request by nick2525**
## Summary

Just use androidx.core.view.isVisible, for less code
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @TESTPERSONAL, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#1685).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @TESTPERSONAL, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#1685).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by JBassett** [comment]
@nick2525 is there any way you can resubmit with the correct git name and email setup?  It looks like your commits are being tied to @TESTPERSONAL.

**Comment by JBassett** [comment]
Or if you haven't signed the CLA that might help as well.

**Review by JBassett — APPROVED** [review]

**Pull request merged**
