### PR TITLE
Migrate to MenuProvider

### PR DESCRIPTION
**Pull request by NotWoods**
## Summary
Migrates the settings pages to use MenuProvider, which replaces the menu override methods on the fragments. Also splits the menus into separate files per fragment group.

## Screenshots
N/A, no changes to menus

## Link to pull request in Documentation repository
N/A

## Any other notes
This should make it possible to get rid of some fragments and go full in on compose soon

### CODE REVIEW

**Comment by jpelgrom** [comment]
FYI one of the menus was changed in #2950 which has now been merged

**Comment by jpelgrom** [comment]
I'm not completely sure why, but the changes in this branch seem to break the notification history screen. It is always completely empty/blank, no matter if there are notifications in the database or not. The menu items do update correctly. When building from the master branch on 07845fb797abb7b0a2d2f0986d38b090fca51496 (current head) the notification history works fine.

Aside from that it's a nice improvement!

**Comment by NotWoods** [comment]
Even setting `findPreference<Preference>("no_notifications")!!.isVisible = true` I can't seem to get the empty state UI to show up. Will keep debugging

**Comment by jpelgrom** [comment]
@NotWoods Hi 👋 Would it be OK for someone else to pick this up, make it work with the latest code and update it for all additions (like was done with the Compose icon dialog), or do you intend to work on this soon?

**Comment by NotWoods** [comment]
Please feel free to pick this up! Sorry I haven't been able to work on it but I hope this is helps someone else.

**Pull request closed without merging**
