### PR TITLE
Allow measured power to be updated via notification command

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Implements: #3290

example service call:

```
service: notify.mobile_app_pixel_8_pro
data:
  message: command_ble_transmitter
  data:
    command: ble_set_measured_power
    ble_measured_power: "-10"
```

The field is validated that its not blank and that it is a negative number

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#1086

## Any other notes

FCM PR: https://github.com/home-assistant/mobile-apps-fcm-push/pull/150

### CODE REVIEW

**Comment by jpelgrom** [comment]
> in some cases the notification will post on the device, in other cases the setting may revert to default

Why have it behave differently, instead of always ignoring it (which is the default behavior with notification commands for invalid values)?

**Comment by dshokouhi** [comment]
> > in some cases the notification will post on the device, in other cases the setting may revert to default
> 
> Why have it behave differently, instead of always ignoring it (which is the default behavior with notification commands for invalid values)?

Added a check to make sure that doesn't happen, should be good now :)

**Comment by dshokouhi** [comment]
That was why i added the check before to capture any other bad value,  added `toIntOrNull` because wanted to avoid a crash. I tested with teh following

- negative numbers - works
- positive numbers - posts notification
- alphanumeric - posts notification
- blank - posts notification

**Comment by jpelgrom** [comment]
But why not do `toIntOrNull() != null` before instead of this convoluted check? The `orNull` is literally there for bad values.

And even if there is a bad (positive) value, it is still set as you don't change the value in line 160?

```kotlin
data[NotificationData.COMMAND] == DeviceCommandData.BLE_SET_MEASURED_POWER &&
    (
        data[DeviceCommandData.BLE_MEASURED_POWER].toIntOrNull() != null && data[DeviceCommandData.BLE_MEASURED_POWER]?.toInt() < 0
        )
```

**Comment by jpelgrom** [comment]
I see my comment is inconsistent with current behavior - invalid changed to something valid for UUID/major/minor.

https://github.com/home-assistant/android/blob/485a84271887478f4715d767b21422d6d9587048/common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt#L144-L145

But that is the exception to the default which ignores the command if invalid (`in` check):

https://github.com/home-assistant/android/blob/485a84271887478f4715d767b21422d6d9587048/common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt#L68

**Comment by dshokouhi** [comment]
Your check is simpler and for some reason I did not consider it, lets go with that as its easier to read :)

**Review by jpelgrom — APPROVED** [review]

**Pull request merged**
