### PR TITLE
Update change log week of 7/14

### PR DESCRIPTION
**Pull request by dshokouhi**
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by JBassett** [comment]
This brings up a good question, when do we want to bump the changelog version from `2023.7.x` to `2023.8.x`?  Technically we could do another production release before the end of the month.

**Comment by dshokouhi** [comment]
> This brings up a good question, when do we want to bump the changelog version from `2023.7.x` to `2023.8.x`? Technically we could do another production release before the end of the month.

great question, not really sure. I am just in the habit of bumping the date after a release lol

**Comment by jpelgrom** [comment]
We could also drop the version number from the titles, as the change log is only shown when updated?

**Comment by dshokouhi** [comment]
> We could also drop the version number from the titles, as the change log is only shown when updated?

I like that, one less thing to change lol. Should we replace `Phone` with `Device` to be more generic? I think `Wear` and `Automotive` are more self explanatory?

**Comment by jpelgrom** [comment]
I would also remove the phone title if possible but I don't think it is. Device feels a bit too generic here 🤔

**Comment by dshokouhi** [comment]
> I would also remove the phone title if possible but I don't think it is.

yea app crashes, its a required field.

Heres one problem, the word `Version` is still listed next to each row. Was trying to test if `Phone\Tablet` was too much (forgot to escape the slash lol) but it looks kinda odd now.

image

**Comment by dshokouhi** [comment]
Device might feel a bit generic but we have to think of a term thats generic since the following device types can be used on that version.

- phone
- tablet
- chromebook
- windows
- anything else, quite literally lol

**Comment by jpelgrom** [comment]
[Looks like 'Version' is hardcoded.](https://github.com/AppDevNext/ChangeLog/blob/master/ChangeLogLib/src/main/java/info/hannes/changelog/ChangeLog.kt#L270) To be fair this is a very simple library - it might be time to create something simple ourselves if we want to customize it.

In the mean time, maybe update the changelog each time with the tag that will be used, so 2023.7.6 now?

> Device might feel a bit generic but we have to think of a term thats generic since the following device types can be used on that version.

Simply 'Companion app', or 'main app'?

**Comment by dshokouhi** [comment]
> In the mean time, maybe update the changelog each time with the tag that will be used, so 2023.7.6 now?

thats easier and a bit more precise :)



> Simply 'Companion app'

I think users may confuse that to mean anything mentioned in the first listing is available everywhere because the app is called Home Assistant Companion.



> or 'main app'?

This sounds more correct 🤷

**Review by JBassett — APPROVED** [review]

**Pull request merged**
