### PR TITLE
Add privacy policy

### PR DESCRIPTION
**Pull request by JBassett**
More Play Store policy changes.
image
image

### CODE REVIEW

**Comment by balloob** [comment]
Maybe also mention in the enable location tracking description that the data is only sent directly to your instance without involvement of any third parties.

**Comment by JBassett** [comment]
@balloob Added the info to the description.

**Comment by balloob** [comment]
Maybe an idea to make the privacy policy not a button, but a link in the description? Now it is a little confusing what the button to go next is.

**Comment by JBassett** [comment]
@balloob good idea, this looks much better:
image

**Pull request merged**
