### PR TITLE
Add Bluetooth sensor

### PR DESCRIPTION
**Pull request by dshokouhi**
Fixes: #452 

- The state of the sensor will be the total number of connected devices including both paired and not paired devices
- Attributes will be `connected paired devices` `connected not paired devices` `paired devices` all provided in a list with the devices mac address. `is bt on` will reflect the state of the bluetooth adapter.
- The sensor will update when bluetooth state changes as well as connection changes are broadcasted.

Connected but not paired devices will include devices like a Mi Band or any other device that pairs with their own app instead of the system itself.  Bluetooth headsets are always paired with the system and so we can see whether they are paired as well as if they are connected.  Bluetooth names are not always given for a device so I have not included them.  There are other bluetooth things we can pull in like device battery (only supported on android 10) however we should think about how we want to expose them to the user.  For now lets just show what is connected and/or paired.

### CODE REVIEW

**Comment by jurgenweber** [comment]
I am super excited! 👍

**Comment by Hypfer** [comment]
I think i've found a bug.
My Garmin Forerunner 235 appears as both a paired as well as not paired device:

image

Don't ask me why though.

Maybe we just need to filter all duplicates from that list?

**Comment by dshokouhi** [comment]
Thanks @Hypfer I can submit a fix for this. We will only count it as a connected paired device in that case.  The mac address will still show up in both lists.  That is probably caused by the device being paired to the app and the android system itself.

**Comment by jesserockz** [comment]
I got the same with my Mi Band, it is paired and connected to the system and connected via BLE to the app so shows up in both.

**Pull request merged**
