### PR TITLE
Use suspend calls for widget daos

### PR DESCRIPTION
**Pull request by NotWoods**
## Summary
Updating the various widget Daos to remove blocking operations, and instead use coroutines. Also tried to make updates so the code is easier to follow.

- Flow and List aren't nullable, so I removed the `?` annotations.
- Updated Compose views so one function handles displaying widget rows for each list

## Any other notes
- https://developer.android.com/reference/androidx/room/Query

### CODE REVIEW

**Comment by dshokouhi** [comment]
Were you able to test the upgrade path from `master` to this branch to ensure the app is still functional post upgrade?

**Comment by NotWoods** [comment]
I'll take a look. Since the DB queries weren't modified I don't expect upgrade issues.

**Comment by NotWoods** [comment]
As far as I can tell the app is functional after upgrades. Created widgets using master then switched to this branch.

**Comment by dshokouhi** [comment]
thank you for checking 🙏

**Review by JBassett — APPROVED** [review]

**Pull request merged**
