### PR TITLE
Implement native Assist

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

This PR adds native Assist to the app;
 - feature parity with [frontend Assist](https://github.com/home-assistant/frontend/blob/dev/src/dialogs/voice-command-dialog/ha-voice-command-dialog.ts)
 - allows voice input over HTTP
 - integrates in Android as a digital assistant app (implements #3513)

These improvements will also be used to update the Assist implementation in the Wear app to the same features where possible after this feature is merged. To facilitate this, code may be more generic in places than expected or added to `common` to allow for easy sharing.

The PR is quite large :( to prevent a breaking change in functionality.

## Screenshots

The aim is to 'merge' the frontend Assist and Android Google Assistant UIs.

Video showing native Assist in the app, voice and text input, dashboard in the background still active (light mode):

https://github.com/home-assistant/android/assets/8148535/81cff131-933e-476f-8b93-9d141984224a

Video showing native Assist as an assistant app from the home screen, switching the pipeline that is used, multiserver support, attribution (dark mode):

https://github.com/home-assistant/android/assets/8148535/aa44aa28-0eca-42a2-8267-b29df425d549

## Link to pull request in Documentation repository

To be added later, might be in home-assistant/home-assistant.io instead

## Any other notes

Tasks completed while PR was in draft:

 - [x] UI review/decisions (request by @balloob was Google Assistant inspired but that does present some challenges because Assist has more elements like pipeline chooser/attribution that need a place - I suggest going for 'good enough' for now and refine in later PR)
 - [x] ~sharing Assist Composables with the Wear app~ -> currently not an option because Material functions are in different dependencies (`androidx.compose.material:material` vs `androidx.wear.compose:compose-material`), only `foundation` can be shared but that isn't good enough.
 - [x] Android task management (triggering Assist outside the app when the app is in the background should bring it up in a standalone task instead of showing the existing app task + Assist)
 - [x] handling more device/network limitations on start as commented in code

### CODE REVIEW

**Comment by jpelgrom** [comment]
UI updates based on Discord feedback: pipeline switcher in dialog header instead of icon button next to input and moved attribution to header as well
|Bottom sheet for Assist now with 'Home Assistant (down arrow icon)' at the top|Bottom sheet for Assist with 'OpenAI (down arrow icon)' in the top left and 'Powered by OpenAI', underlined, in the top right|
|-----|-----|

**Review by JBassett — APPROVED** [review]
This was quite the PR!

**Comment by felipecrs** [comment]
This is amazing, congratulations on the PR!

**Comment by dnestico** [comment]
Amazing, I was hoping this exact thing was possible for Assist and you did it!

**Comment by jpelgrom** [comment]
@dnestico Most of the sentences you're using aren't supported by Assist, see [the documentation](https://www.home-assistant.io/voice_control/builtin_sentences#view-existing-sentences) for an overview and steps to verify if a sentence you used is supported. If you find something that is working with Assist in the browser but isn't working in the app, feel free to open a new issue, a merged pull request isn't the place to report something like this.

**Comment by dnestico** [comment]
I thought the math one would work cuz I saw someone else do it, regarding the weather one I know it didn''t work cuz I didn't add it as a intent yet under the conversation yaml in condig.yaml. But thanks also sorry.

**Comment by jpelgrom** [comment]
> math one would work cuz I saw someone else do it

It might also be because they were using a different [conversation agent](https://www.home-assistant.io/integrations/#voice) that does support it, like the Google Assistant or OpenAI. There are a lot of possibilities :)

**Pull request merged**
