### PR TITLE
Allow Phone to Onboard Wear Device

### PR DESCRIPTION
**Pull request by JBassett**
## Summary

With this PR we now know if the Wear OS device we are connected to is authenticated.  If not then we allow them to go through the onboarding flow on the phone!
Fixes: https://github.com/home-assistant/android/issues/1782

## Screenshots

Reusing the existing onboarding flow, no changes there.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by dshokouhi** [comment]
Just got a moment to test this.

When I go to wear OS settings we should probably update the message to reflect logging in as we still talk about managing favorites :)

image

Also when we trigger the login method we are triggering onboarding again which means that the user sees the location toggle however there is no location support on Wear OS yet :) so we should probably remove that bit.

After logging in the settings screen briefly shows the login button again but then a few seconds later updates to show the favorites button, not sure if we can speed that up or not but wanted to mention it :)

I also dont think the user should select their HA instance again, shouldn't we preselect it so the watch and phone are on the same instance?

After backing out of settings to go back to HA frontend I noticed we reloaded webview again and I saw this error

```
2021-12-10 10:04:03.226 21626-21626/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 21626
    java.lang.RuntimeException: Unable to destroy activity {io.homeassistant.companion.android.debug/io.homeassistant.companion.android.settings.wear.views.SettingsWearMainView}: java.lang.ClassCastException: io.homeassistant.companion.android.HomeAssistantApplication cannot be cast to android.app.Activity
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5387)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5420)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassCastException: io.homeassistant.companion.android.HomeAssistantApplication cannot be cast to android.app.Activity
        at io.homeassistant.companion.android.settings.wear.SettingsWearViewModel.onCleared(SettingsWearViewModel.kt:86)
        at androidx.lifecycle.ViewModel.clear(ViewModel.java:138)
        at androidx.lifecycle.ViewModelStore.clear(ViewModelStore.java:62)
        at androidx.activity.ComponentActivity$4.onStateChanged(ComponentActivity.java:261)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:224)
        at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1516)
        at android.app.Activity.performDestroy(Activity.java:8312)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5374)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5420) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by dshokouhi** [comment]
This should also fix #1782 right?

**Comment by dshokouhi** [comment]
After adding favorites from the phone I get a crash.

```
2021-12-10 10:33:09.592 24985-24985/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 24985
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
        at [Source: (String)"[{"id":"input_boolean.bedroom_humidifier","position":0}]"; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1292)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:216)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3613)
        at io.homeassistant.companion.android.settings.wear.SettingsWearViewModel.onLoadConfigFromWear(SettingsWearViewModel.kt:195)
        at io.homeassistant.companion.android.settings.wear.SettingsWearViewModel.onDataChanged(SettingsWearViewModel.kt:156)
        at com.google.android.gms.wearable.internal.zzhx.notifyListener(com.google.android.gms:play-services-wearable@@17.1.0:2)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(com.google.android.gms:play-services-base@@17.5.0:18)
        at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(com.google.android.gms:play-services-base@@17.5.0:6)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

Even if I start with adding favorites from the watch I get this crash going to wear settings on the phone

```
2021-12-10 10:36:27.430 26695-26695/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.homeassistant.companion.android.debug, PID: 26695
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
        at [Source: (String)"[{"id":"input_boolean.bedroom_fan","position":1}]"; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1292)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:216)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3613)
        at io.homeassistant.companion.android.settings.wear.SettingsWearViewModel.onLoadConfigFromWear(SettingsWearViewModel.kt:195)
        at io.homeassistant.companion.android.settings.wear.SettingsWearViewModel.onDataChanged(SettingsWearViewModel.kt:156)
        at com.google.android.gms.wearable.internal.zzhx.notifyListener(com.google.android.gms:play-services-wearable@@17.1.0:2)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(com.google.android.gms:play-services-base@@17.5.0:18)
        at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(com.google.android.gms:play-services-base@@17.5.0:6)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by leroyboerefijn** [comment]
Awesome update! 😁

I probably won't have time to test it myself, but one thing occurred to me when reading through the changes. It would be great if we add a button on the wear os onboarding Activity that says something like "authenticate on phone". Which will then open the correct view on the phone app.

**Comment by JBassett** [comment]
> When I go to wear OS settings we should probably update the message to reflect logging in as we still talk about managing favorites :)

Fixed

> Also when we trigger the login method we are triggering onboarding again which means that the user sees the location toggle however there is no location support on Wear OS yet :) so we should probably remove that bit.

Rather than bastardize the onboarding to support some of this I saw we just work on getting location support (outside of this PR)

> After logging in the settings screen briefly shows the login button again but then a few seconds later updates to show the favorites button, not sure if we can speed that up or not but wanted to mention it :)
Fixed

> I also don't think the user should select their HA instance again, shouldn't we preselect it so the watch and phone are on the same instance?

For now I saw we keep it, it allows the user to use a different URL than they use for the phone since they don't operate 1-1 the same.

> After backing out of settings to go back to HA frontend I noticed we reloaded webview again and I saw this error

Fixed

> After adding favorites from the phone I get a crash.

Fixed

> Even if I start with adding favorites from the watch I get this crash going to wear settings on the phone

Fixed

> It would be great if we add a button on the wear os onboarding Activity that says something like "authenticate on phone". Which will then open the correct view on the phone app.

Sounds like a new feature request, really trying to just get the foundation laid here.

**Comment by dshokouhi** [comment]
All issues I previously reported are fixed :) 

One thing that I did notice is that onboarding for the watch defaults  the device name to the phone name which means if a user doesn't change it they will end up with the same sensors just with `_2` we should probably correct that to prevent users getting confused.

During testing I encountered one error on the watch which I was not able to reproduce again. I assume it may have been me adding a favorite from the phone to watch before the watch was able to load entity details? Probably out of scope here as I assume the same issue may occur in `master` although tough to tell because we are usually logged in by the time we go on the phone to mess with stuff lol.

```
2021-12-09 20:06:16.564 12564-19701/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
    Process: io.homeassistant.companion.android, PID: 12564
    java.lang.IllegalArgumentException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
        at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:241)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:47)
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:286)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
        at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:116)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4389)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4335) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.handleEvent(WebSocketRepositoryImpl.kt:241) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$handleEvent(WebSocketRepositoryImpl.kt:47) 
        at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$onMessage$1.invokeSuspend(WebSocketRepositoryImpl.kt:286) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```



> Rather than bastardize the onboarding to support some of this I saw we just work on getting location support (outside of this PR)

I agree, we can just mention its coming if anyone says something about it :)

> For now I saw we keep it, it allows the user to use a different URL than they use for the phone since they don't operate 1-1 the same.

thats fine :)

> Sounds like a new feature request, really trying to just get the foundation laid here.

Agreed, I do like the idea of telling the user they can use their phone :) we had a few comments about entering long passwords on a watch being 'fun'

**Comment by JBassett** [comment]
@dshokouhi  fixed that last crash here: https://github.com/home-assistant/android/pull/2004 unrelated to what I was working on in this PR.
Also fixed comments.

**Review by dshokouhi — APPROVED** [review]
Tested latest debug APK, all issues are resolved!

**Pull request merged**
