### PR TITLE
Fix button widget on Samsung devices

### LINKED ISSUE #4075: "Service Button" widget missing on Samsung devices when adding widgets from home screen
**Home Assistant Android app version(s):**
2023.10.2-full
**Android version(s):**
14
**Device model(s):**
Samsung Galaxy S21
**Home Assistant version:**
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2
**Last working Home Assistant release (if known):**
Not known...
**Description of problem, include YAML if issue is related to notifications:**
The "Service Button" widget is missing from the widget editor. The editor however shows that there should be 6 widgets next to the name of the app.  

**Companion App Logs:**
There are no logs as the button for adding the widget is just missing

**Screenshot or video of problem:**
WhatsApp Image 2023-12-26 at 14 11 59_050c2756
WhatsApp Image 2023-12-26 at 14 11 59_ec9c0a04

**Additional information:**
I already tried:
- Reinstalling HA app
- Updating android system and Samsung "sub OS"
- Restarting my device

### PR DESCRIPTION
**Pull request by SkechyWolf**
## Summary

This should fix #4075

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by jpelgrom** [comment]
Can you explain why this fixes it? It is supposed to be 1x1, and these priorities should be optional (added in a recent version).

**Comment by SkechyWolf** [comment]
I tried with 1x1 and it shows the same way before this change (broken in widget selector)

**Comment by jpelgrom** [comment]
That's a shame, but also suggests this is really a Samsung bug as 1x1 widgets should be visible.

**Review by jpelgrom — APPROVED** [review]
Samsung's too big to ignore

**Review by JBassett — APPROVED** [review]

**Comment by jamesorlakin** [comment]
Unfortunately on my phone with Xperia Home it now forces the button widget to be a 2x1 as intended. Existing widgets are fine (though I've avoiding trying to resize them!), but new buttons are now forced to be unfairly tall and rectangular.

Would there be scope to revert this? I appreciate Samsung has a large user base but the declared value is now incorrect.
image
image

**Pull request merged**
