### PR TITLE
Improvements of some Dutch translations

### PR DESCRIPTION
**Pull request by corneyl**
### Summary
This PR contains some improvements in the Dutch translation strings because they contained small mistakes or felt a bit unnatural.

### Screenshots

N/A

### Link to pull request in Documentation repository

N/A

### Any other notes

About the translations:
- 'Sensors' seemed to me a more commonly used plural of sensor than 'sensoren'.
- 'Batterijstatus' was used twice in separate context, the distinction has been made more clear.
- In Dutch only the first word in a title is written with a capital
- Some capitals in abbreviations were fixed or made a bit more consistent

### CODE REVIEW

**Comment by dshokouhi** [comment]
Hey there thanks for the PR but unfortunately we do not update our translated strings here we use [lokalise](https://lokalise.com/public/145814835dd655bc5ab0d0.36753359/) where you can submit updates.  Only english is updated in this repo.  Please join us on lokalise to update the strings for the language you like.

**Comment by corneyl** [comment]
Hmmm, that's a pity, hadn't seen it in the readme...

**Comment by dshokouhi** [comment]
> Hmmm, that's a pity, hadn't seen it in the readme...

you mean right here 😃 

https://github.com/home-assistant/android#translating

**Comment by JBassett** [comment]
It does bring up a question about only keeping English in the repo and at build time pull down from Lokalise.... That way there is no confusion.  Would keep me from forgetting to pull from Lokalise when we release too, haha.

**Comment by dshokouhi** [comment]
The more automation the merrier!

**Comment by corneyl** [comment]
> > Hmmm, that's a pity, hadn't seen it in the readme...
> 
> you mean right here 😃
> 
> https://github.com/home-assistant/android#translating

Yes, that 😃 hadn't seen it. But I'll try to fix some things in Lokalise.

**Pull request closed without merging**
