### PR TITLE
UseCase can't lay in data layer

### PR DESCRIPTION
**Pull request by nick2525**
very minor changes according clean architecture

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @TESTPERSONAL, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#1375).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by nick2525** [comment]
in is not my lint errors  /home/runner/work/android/android/app/src/full/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt:81: Error: Missing permissions required by intent Intent.ACTION_CLOSE_SYSTEM_DIALOGS: android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS [MissingPermission]
          context.sendBroadcast(Intent(Intent.ACTION_CLOSE_SYSTEM_DIALOGS))
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Applies to variants: fullDebug, fullRelease
  /home/runner/work/android/android/app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt:141: Error: Value must be ≥ 0 [Range]
                                  cv.put("id", widgets.getInt(widgets.getColumnIndex("id")))
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/work/android/android/app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt:142: Error: Value must be ≥ 0 [Range]
                                  cv.put("entity_id", widgets.getString(widgets.getColumnIndex("entity_id")))
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dshokouhi** [comment]
Is your branch fully up to date? I think you may need to update the branch with latest changes to solve the errors. Everything needs to pass with green check marks.

**Comment by nick2525** [comment]
I checked now, it is full up to date

**Comment by nick2525** [comment]
something wrong with CI

**Comment by dshokouhi** [comment]
> something wrong with CI

yea seems something may have been updated, feel free to leave this open while we look into it

**Pull request closed without merging**
