### PR TITLE
Add icon meta file

### PR DESCRIPTION
**Pull request by NotWoods**
## Summary
Adds code to start migrating off the icon dialog library, which is out of date. This change adds a mapping from the lib's integer IDs to regular MDI icon names.

I generated the meta file in [NotWoods/home-assistant-android-icon-map](https://github.com/NotWoods/home-assistant-android-icon-map)

## Screenshots
N/A

## Link to pull request in Documentation repository
N/A

## Any other notes
Related to #2709

### CODE REVIEW

**Comment by jpelgrom** [comment]
Thanks for your work so far!

I see a lot of unused data in the json file, if not needed data should be removed to limit the binary size. Do you intend to use this for something else in the future?

If so, presumably this file will need to be updated in the future with new MDI releases? Would it make sense to also include the code to generate the file in this repository?

If not, there is a lot of data that could be removed as we only really need the icon dialog lib ID and MDI name. To remove the need to load this data each time, maybe even migrate the database data to store the MDI name instead?

**Comment by NotWoods** [comment]
I'm planning to use the aliases and tags for the icon dialog. I wasn't able to see a clear way to run migrations using asynchronous code, but I agree that it makes sense to store the icon name instead. Happy to include the generating code inside this repo but wasn't sure what language to use.

**Comment by jpelgrom** [comment]
> I wasn't able to see a clear way to run migrations using asynchronous code

I don't think that is possible, as the database schema can't be changed while the database is open. Room will actively throw errors if the database doesn't match the schema. Most users don't have any widgets/tiles setup or only a few, so I think the impact of doing this synchronously (= on app launch, which is when Room performs migrations) is acceptable.

> Happy to include the generating code inside this repo but wasn't sure what language to use.

Most developers will use Android Studio / IntelliJ IDEA to develop and build the app so if you can make it easy to run from there that would be nice. Your existing Javascript code also looks good to me if that is what you prefer, but maybe you could add a little more info to the README explaining how to setup the environment to run it for those not familiar with JS?

**Comment by NotWoods** [comment]
Replacing with #3016. I'll include a python script for generation later, since its used with the main repo

**Comment by jpelgrom** [comment]
I know it's still draft but did you drop the tags/alias filtering idea? The JSON file in there is a lot simpler / just a map for conversion, not metadata.

**Comment by NotWoods** [comment]
I dropped it for now because of the size of the PR; I'd rather get this ready first and add additional search filters later. I think the metadata will end up in a separate file so it can be loaded independently of the migration code

**Pull request closed without merging**
