### PR TITLE
Update icon

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

 - Replace old icon with [the new icon](https://www.home-assistant.io/blog/2023/09/17/a-refreshed-logo-for-home-assistant/)
 - Deduplicate icon resources

## Screenshots

Everywhere the Home Assistant icon was, or the primary color was used, it should now be changed. For example in the launcher, old vs new:
Old Home Assistant icon on the left, new Home Assistant icon on the right

And as a notification icon:
Status bar with various notification icons, including one from Home Assistant

## Link to pull request in Documentation repository

n/a

### CODE REVIEW

**Comment by jpelgrom** [comment]
Changing to draft to receive clarification on what the frontend will do re. primary color

**Comment by LasseRosenow** [comment]
I think now that we have a new logo, maybe we should discuss the "centering in a circle" problem.

On the old icon it was much more obvious, but still the new icon still suffers this problem I think.
Even though it is `technically` centered, it does not look quite centered.

There is a very good post on medium about this:
https://medium.com/@erqiudao/the-play-button-is-not-optical-alignment-4cea11bda175

So in general we should try to center the center of the house by drawing a circle around it and using the circles center point as the center and not by drawing a rectangle and centering this :)

How do you think about this?

**Comment by LasseRosenow** [comment]
I created an example of how the icon would look using a circle to center it:

| Current | "Fixed" |
|---|---|
|  launcher_new_broken | launcher_new_fixed  |
| launcher_new_broken_red_border  |  launcher_new_fixed_red_border |

**Comment by jpelgrom** [comment]
Thanks. Turns out they did create a circle-specific design I wasn't aware of.

**Comment by dshokouhi** [comment]
Should we also update our play store listing icon with this PR?

**Comment by jpelgrom** [comment]
It is also updating the listing icon, isn't it?

**Comment by dshokouhi** [comment]
yes it is, shouldve searched before commenting 🤦

**Comment by jpelgrom** [comment]
Frontend isn't changing primary color, decoupled.

**Comment by Madelena** [comment]
Looking good 👍

**Review by dshokouhi — APPROVED** [review]

**Review by JBassett — APPROVED** [review]

**Pull request merged**
