### PR TITLE
Allow UUID, Major and Minor to be changed via notification command

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Fixes: #2470 by introducing new parameters for BLE command.

- `ble_set_uuid` with `ble_uuid` to change the UUID
- `ble_set_major` with `ble_major` to change Major
- `ble_set_minor` with `ble_minor` to change Minor

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#783

## Any other notes

FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/84

### CODE REVIEW

**Comment by jpelgrom** [comment]
While changing the settings works, I found that I had to actively stop and start the transmitter to have them used. Is this intentional? I would have expected it to change automatically and immediately when receiving the command.

**Comment by dshokouhi** [comment]
> While changing the settings works, I found that I had to actively stop and start the transmitter to have them used. Is this intentional? I would have expected it to change automatically and immediately when receiving the command.

According to the code, it should restart next time the sensor checks in for an update.

https://github.com/home-assistant/android/blob/c1b4ea5626767e3358b205576a523918b25f5250/app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt#L206-L212

  Let me try and test it out by forcing a sensor update after the DB was updated.

**Comment by jpelgrom** [comment]
> According to the code, it should restart next time the sensor checks in for an update.

That's also what I was able to find, guess I wasn't missing anything then. As I said I was expecting it to work immediately, so not having to wait on the SensorWorker, but if that is by design it's OK.

**Comment by dshokouhi** [comment]
So had to make sure the transmitter restarts properly, but also need to make sure the attributes can be sent during the restart. The restart happens very fast, the state change is actually not sent to HA  but we can see in the logs that it restarted properly.

```
2022-07-26 09:17:12.134 16226-16226/io.homeassistant.companion.android.debug I/BeaconTransmitter: Advertisement start succeeded.
```

**Review by jpelgrom — APPROVED** [review]
Works as expected

**Review by JBassett — APPROVED** [review]

**Pull request merged**
