### PR TITLE
added android automotive os

### PR DESCRIPTION
**Pull request by rchiileea**
made compatible with android automotive OS (whole car operating system used by google, polestar, renault as well ass many more manufactures joining in this year, simply a must to start including this, especially sensor wise

## Summary

added support for the android automotive os (which is not android auto but rather a whole car system os) currently used by Volvo, Renault, Pulstar, Lucid, with all the bellow manufacture commiting to using it starting this year.

(Abarth, Acura, Alfa Romeo, Aston Martin, Audi, Bentley, Buick, BMW, Cadillac, Chevrolet, Chrysler, Citroën, Dodge, Ferrari, Fiat, Ford, GMC, Genesis, Holden, Honda, Hyundai, Infiniti, Jaguar Land Rover, Jeep, Kia, Lamborghini, Lexus, .)

## Screenshots

image

image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes
Added moudle to convert and enable use of app in Android automotive OS

### CODE REVIEW

**Comment by jpelgrom** [comment]
Did you add all files? The module doesn't use any of our other modules and I'm not seeing any new code, I think you simply deployed the normal app to the emulator.

Also please remove unnecessary/unused files like your personal Firebase credentials, test placeholders, etc.

**Comment by rchiileea** [comment]
> Did you add all files? The module doesn't use any of our other modules and I'm not seeing any new code, I think you simply deployed the normal app to the emulator.
> 
> Also please remove unnecessary/unused files like your personal Firebase credentials, test placeholders, etc.

you cant deploy normal apps to android automotive os, they will just fail, is there not a folder called automotive added?

I am new to this completely, so you want me to remove the google services ? (i have only been making icons for hacs repo until now).

**Comment by dshokouhi** [comment]
> you cant deploy normal apps to android automotive os, they will just fail, is there not a folder called automotive added?



I see only 25 files modified here without a reference to our main app module or even our `WebViewActivity` as shown in the screenshots. Did all the files get committed as expected?



> I am new to this completely, so you want me to remove the google services ? (i have only been making icons for hacs repo until now).

yup we do not need the google services file in a PR it should be ignored from github like in the app and wear folder.

also I believe for us to test this in an emulator we will need a separate APK generated in the github action, as of now there are no references to the automotive module there.

**Comment by jpelgrom** [comment]
After [discussion on Discord](https://discord.com/channels/330944238910963714/377667559303938050/1072547327811796992) it looks like the normal `app` module was deployed when testing/for the screenshots. This obviously works when sideloading (it's Android) but doesn't add anything new and won't be accepted on the Play Store [1](https://developer.android.com/training/cars/apps/automotive-os#car-app-activity), [2](https://developer.android.com/docs/quality-guidelines/car-app-quality). Other limits mentioned on the [media apps for Android Automotive OS page](https://developer.android.com/training/cars/media/automotive-os) like WebView may only be used for sign-in and settings presumably also apply.

Marking this as draft until issues are resolved and there is actually code in the `automotive` module. If you have questions, feel free to reach out!

**Comment by jpelgrom** [comment]
Closing this in favor of #3423 which achieves the same goal

**Pull request closed without merging**
