### PR TITLE
Pause the webview by loading a null page, killing javascript/websocket.

### PR DESCRIPTION
**Pull request by JBassett**
Fixes: https://github.com/home-assistant/android/issues/542
Fixes: https://github.com/home-assistant/android/issues/277

This seems to be the only way I can actually get the websocket to be closed.  We basically navigate away when the application gets paused, and reload the app on resume.

### CODE REVIEW

**Comment by balloob** [comment]
Is this something we can do on a timer? Say, 5 minutes? 

I also wonder if it might be better to built something into the frontend to help with this. Kill all camera feeds + websocket connection. Not sure if it would be possible.

**Comment by andriej** [comment]
Especially that issue you've linked shows that some other websocket connections may cause it (not related to only android app).

**Comment by JBassett** [comment]
We can delay 5 minutes.  I agree that a hook to the frontend would be the best solution to pause and resume the connection.  I'll add the timer to the PR at some point today.

**Comment by JBassett** [comment]
One day, two months.... What is time anyway?

**Comment by balloob** [comment]
@bramkragten is actually working on a PR for the frontend to implement https://github.com/home-assistant/frontend/issues/5438 / https://github.com/home-assistant/frontend/issues/5437

**Comment by bramkragten** [comment]
The frontend now manages this, so I think this PR is not longer needed.

**Comment by JBassett** [comment]
Closing in favor of the frontend fix

**Pull request closed without merging**
