### PR TITLE
Use receiver exported for all sensor receiver intents

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

After #4559 was added I was doing more research into the [missing intent issue](https://github.com/home-assistant/android/issues/4040). I know that issue predates the android 14 SDK requirement however I noticed the following google docs page that was updated this month 🙃 

https://developer.android.com/develop/background-work/background-tasks/broadcasts#context-registered-receivers

specifically this part in step 4 stood out the most to me.

` If this receiver is listening for broadcasts sent from the system or from other apps—even other apps that you own—use the RECEIVER_EXPORTED flag.`

and then followed by

`If instead this receiver is listening only for broadcasts sent by your app, use the RECEIVER_NOT_EXPORTED flag.`

based on the above alone we should always export all intents because they are not sent by our own app.

The note underneath step 4 also confirms we need to use the same exported flag because we cannot intermix in the same receiver.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

important to note that in my own setup I have not noticed an issue in the internal track, testing this PR also shows intents working the same.

### CODE REVIEW

**Comment by jpelgrom** [comment]
I can sort of follow your logic for the sensor receiver here, but you're also updating others where there is no mixing? The page also includes a note between the two parts you mentioned that non-privileged system broadcasts will work with `NOT_EXPORTED` which is the list in the original PR and I think these are working fine right now (like widgets).

**Comment by dshokouhi** [comment]
ok let me rollback the changes for widgets and complications, when reading the change they really make it seem like you need to use `RECEIVER_EXPORTED` so you dont miss any intents. Even when it talks about when its ok to use `RECEIVER_NOT_EXPORTED` it still makes it sound like you can miss intents so I figured for any system intents we should always use exported instead of not.

**Comment by jpelgrom** [comment]
For battery intents: the receiver is `null` here because we only care about the sticky intent, so do we need to change this at all? It seems to be working as it is right now and there is no mixing of receivers like in the other situations.

**Comment by dshokouhi** [comment]
> For battery intents: the receiver is `null` here because we only care about the sticky intent, so do we need to change this at all? It seems to be working as it is right now and there is no mixing of receivers like in the other situations.

tough to tell the missing intent issue had some mentions of the charger intents 🤔 

https://github.com/home-assistant/android/issues/4040#issuecomment-2091881265 and https://github.com/home-assistant/android/issues/4040#issuecomment-2257295879

however you have a good point on the `null` receiver so it may not be necessary as you mentioned :)

**Review by jpelgrom — APPROVED** [review]
OK, let's do this to be safe and not mix exported/not exported in the same receiver

**Pull request merged**
