### PR TITLE
Update Detected activity sensor icon based on state

### PR DESCRIPTION
**Pull request by mikosoft83**
## Summary
Harmonize icons between android and ios

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by dshokouhi** [comment]
is this an iOS provided  icon? trying to find it in the code base but dont see it

**Comment by jpelgrom** [comment]
It is in the app specific icons:

https://github.com/home-assistant/iOS/blob/b5f680174b26c82d33acbcc19f253faad1ab7385/Sources/Shared/Common/Extensions/CMMotion%2BStringExtensions.swift#L39-L40

@dshokouhi You're more familiar with this sensor than I am, is `still` the same as being `stationary` or does it reflect something else (sleeping which the current icon shows)?

**Review by dshokouhi — APPROVED** [review]

**Comment by mikosoft83** [comment]
Updated app today, this is how it looks on my dashboard now, I am very happy :D 
image

**Comment by marazmarci** [comment]
> Updated app today, this is how it looks on my dashboard now, I am very happy :D 
> image
> 

Wow, this looks cool! Can I ask how did you set this up?

**Comment by mikosoft83** [comment]
> > Updated app today, this is how it looks on my dashboard now, I am very happy :D
> > image
> 
> Wow, this looks cool! Can I ask how did you set this up?

It uses multiple entity row from HACS, you can put several entities in one entity row and the whole thing is just entities card.

YAML looks like this:
```
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: sensor.iphone_42_geocoded_location
    show_state: false
    name: Ria's iPhone
    icon: cil:iphone-modern
    entities:
      - entity: sensor.iphone_42
        name: false
        icon: true
      - entity: sensor.iphone_42_connection_type
        name: false
        icon: true
      - entity: sensor.iphone_42_activity
        name: false
        icon: true
      - entity: sensor.iphone_42_battery_level
        name: false
        icon: true
  - type: custom:multiple-entity-row
    entity: sensor.oneplus_geocoded_location
    show_state: false
    name: Milan's OnePlus
    icon: mdi:cellphone
    entities:
      - entity: sensor.oneplus_ringer_mode
        name: false
        icon: true
      - entity: sensor.oneplus_do_not_disturb_sensor
        name: false
        icon: true
      - entity: binary_sensor.oneplus_android_auto
        name: false
        icon: true
      - entity: sensor.oneplus_network_type
        name: false
        icon: true
      - entity: sensor.oneplus_detected_activity
        name: false
        icon: true
      - entity: sensor.oneplus_battery_level
        name: false
        icon: true
```

**Pull request merged**
