### PR TITLE
Fix version code for F-Droid builds

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

The new release model #3597 removed `version_code.txt`, which [broke F-Droid's update detection](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/io.homeassistant.companion.android.minimal.yml?ref_type=heads#L416). We could tell them to update to use our version names and `version.txt` but this is easier as this file was specifically added for them.

## Screenshots

n/a

## Link to pull request in Documentation repository

n/a

### CODE REVIEW

**Comment by jpelgrom** [comment]
Also if this is approved we should upload a `version_code.txt` for the 2023.7.5 release to be nice :)

**Comment by dshokouhi** [comment]
> Also if this is approved we should upload a `version_code.txt` for the 2023.7.5 release to be nice :)

Do we need to wait? Can we just upload one beforehand? Will their build trigger if we edit an existing release?

**Comment by jpelgrom** [comment]
I don't know if it will trigger a build for them but no harm in adding it?

**Comment by dshokouhi** [comment]
> I don't know if it will trigger a build for them but no harm in adding it?

ok added it

**Comment by jpelgrom** [comment]
Version code for app-minimal-release.apk downloaded from that release is 10506, not 10507?

**Comment by dshokouhi** [comment]
> Version code for app-minimal-release.apk downloaded from that release is 10506, not 10507?

oops thats what I get for looking at the Play Console 😂

**Review by dshokouhi — APPROVED** [review]

**Review by JBassett — APPROVED** [review]

**Pull request merged**
