### PR TITLE
Breaking Change: Update heart rate sensor for Wear OS 4+ target

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

Update the permission requirements for the heart rate sensor on Wear OS 4+ to handle the new behavior when targeting it. These permissions need to be requested in two stages like background location. Any user with the sensor currently enabled on Wear OS 4+, will need to re-enable it after updating.

## Screenshots

n/a

## Link to pull request in Documentation repository

~~Documentation: home-assistant/companion.home-assistant#1087~~ n/a

### CODE REVIEW

**Review by dshokouhi — APPROVED** [review]
Well this sucks, hopefully Google will change that some day or hopefully health connect will allow it to be pulled. I agree lets merge alongside the API bump.

**Comment by dshokouhi** [comment]
Given what we know in https://github.com/home-assistant/android/issues/4500#issuecomment-2303848622 should we hold off on this?

**Comment by jpelgrom** [comment]
Oh I completely forgot about your comment, I still wanted to test this because I couldn't find it the first time. I'll do that in a couple of hours and comment.

**Comment by jpelgrom** [comment]
You're right, I must have missed something during previous tests (or an update happened). Handling this like background location with requesting the main permission first, then the background permission, seems to work. Updating the PR to change it.

(Still a breaking change in a way: because a permission is added, users need to toggle the sensor on again.)

**Review by dshokouhi — APPROVED** [review]
Thank you for testing and updating the PR so we don't lose a feature :)

**Pull request merged**
