### PR TITLE
Architecture Simplification

### PR DESCRIPTION
**Pull request by JBassett**
Several of the developers that have recently started contributing brought up the fact that it was very intimidating to look into the data/domain modules.  Where I understand the intent behind them, the boilerplate code and confusion it can cause developers was too great.  Hopefully this will make contributing easier for people.

### CODE REVIEW

**Comment by skynetua** [comment]
@JBassett consider to leave shortcuts files for a while. I'll reuse part of them for #918 and remove unnecessary in the next pr.

**Comment by dshokouhi** [comment]
@skynetua I believe for shortcuts we still need a frontend and core change to complete it.  Did you review all the discussion that went on when that feature was being added?

**Comment by skynetua** [comment]
For now i'll add tools for it customization and replicate button widget functions.

**Comment by dshokouhi** [comment]
> replicate button widget functions

I like that! I was actually thinking another useful location to replicate the service call widget would be for some quick setting tiles 😃

**Comment by JBassett** [comment]
> @JBassett consider to leave shortcuts files for a while. I'll reuse part of them for #918 and remove unnecessary in the next pr.

I think it'll make your PR easier to review if you add the full functionality.  Feel free to take the code that was there for your PR though.

**Pull request merged**
