### PR TITLE
Minimal Android Flavor

### PR DESCRIPTION
**Pull request by JBassett**
Address the following: #231, #358, #570, #599, #600, #676

I understand many people do not like Google and the services they ship on most Android devices.  This is me extending an olive branch to those people.  This pull request adds two flavors to our wonderful application.  

First up is `Full`, this should be exactly the same as we ship today.  It's full of Google services, but in return has full support for everything we had before (Push notifications via FCM, Google Location services, and Crashlytics to help us).  

Second we have `minimal`.  This is a stripped down version that has no connections or dependencies on Google services.  By using this version you are paying the price of not having push notifications, no location tracking, and most importantly no `priority` support.  My main effort for now is still on the version of the application we publish via the Play Store.  I'm not saying every PR will break this version but it will be less thoroughly tested.

I hope that by doing the leg work to keep the code in a single repo we can have more developers who are excited about developing for the application in general.  A rising tide lifts all boats.  Hopefully this will help drive developers to continue to give back to the community and help move this application forward!

### CODE REVIEW

**Comment by tadly** [comment]
Will this be a official release in the play store at some point?

**Comment by JBassett** [comment]
@tadly No, the APKs will be hosted on Github for now.  Publishing to the play store would be ironic since the whole reason behind the minimal build is to remove Google dependencies.  We will work on surfacing them better but you can find the builds under the actions section: https://github.com/home-assistant/android/actions/runs/193845592 for example

**Comment by tadly** [comment]
Does publishing on the play store imply creating a building with google services? Sorry if that's a dumb question ':D

I assume f-droid might be the way to go then?

The reason I am interested in the minimal version is mostly because I don't need all that additional functionality and would rather have the app not "register" at all with the backend (just be a dumb frontend).
f-droid is kind of a pain as non of the store apps are all that good so I personally would prefer installing it through the play store if at all possible.
Just my 2 cents :)

Thanks for the work though (:

**Comment by balloob** [comment]
The Home Assistant frontend is a progressive web app, that you can install on Android as an app with Firefox or Chrome (probably others too). You don't need the app if you just want the UI.

**Comment by tadly** [comment]
I am aware of this, just never was a fan of it.
While the app is basically just a webview too, it starts quite a bit faster and does give me the "Home Network" ability so I do prefer the app in that sense.

I'm also hopeful for further improvements in regards to widgets, app startup-time (maybe due to more aggressive caching. it *could* be made almost instant), etc. which is why I'd like to stick with it :)

But this is quite off-topic and I don't want to bore you guys with it. :)
A minimal version is really nice to have be it in the play store or not

**Comment by jleeuwes** [comment]
@JBassett thank you for this effort!

@tadly I don't know if you are interested in this, but the `minimal`-flavored app is being added to the F-Droid repository: https://github.com/home-assistant/android/issues/897

**Pull request merged**
