### PR TITLE
Update change log week of 10/1 for beta

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Bumps release to 2022.10.1 in case we release again this month, resets the changelog for next release.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by jpelgrom** [comment]
Here's a new issue: beta users probably won't see the full changelog for 2022.10 considering the releases are only a few hours apart. Should we maybe keep the 2022.10 changes in the app's changelog as well for one more week?

**Comment by dshokouhi** [comment]
> Here's a new issue: beta users probably won't see the full changelog for 2022.10 considering the releases are only a few hours apart. Should we maybe keep the 2022.10 changes in the app's changelog as well for one more week?

good point! will restore those changes above since they are breaking changes and we dont want them to miss that

**Review by jpelgrom — APPROVED** [review]

**Comment by JBassett** [comment]
If we're going to leave them in can we leave them in a separate release block?

**Comment by dshokouhi** [comment]
> 

let me see how it looks

**Comment by dshokouhi** [comment]
image

**Review by JBassett — APPROVED** [review]

**Pull request merged**
