### PR TITLE
Make command_high_accuracy_mode behave as "force on" and "don't force on"

### PR DESCRIPTION
**Pull request by chriskemp**
## Summary

When using constraints (zones or bluetooth) with high accuracy mode, it makes sense to have the highAccuracyModeSetting _on_, but high accuracy mode is not 'active' (waiting for a zone or bluetooth).  In this case it is currently not possible to use the command_high_accuracy_mode notification.  Sending "turn_on" sets the forceHighAccuracyModeOn flag and highAccuracyModeSetting to on (which it already is) and hence the device starts high accuracy mode.  However, sending "turn_off" clears both flags and hence disables future constraint (zones or bluetooth) updates.

This PR makes turn_on and turn_off behave as I suspect was intended - as "force on" and "don't force on".  

An alternative might be to add alternative "force_on" and "dont_force_on" commands.  In that case I guess turn_on and turn_off shouldn't change the internal forceHighAccuracyModeOn flag?

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @chriskemp

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/android#2906).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by dshokouhi** [comment]
So the goal behind having on device automations and the notification command is so that the 2 can work together. Meaning if high accuracy was turned on because a BT device got connected, then if a user forces it off via notification command it should not turn back on until the next time it triggers. Its meant to act as a override so when you do your testing you will want to test the combination of on device automation in addition to the command. Its a bit tricky modifying things in this area because of the potential of breaking something already working for a user. You may want to spend some time looking at closed issues to familiarize yourself with the varying use cases around this feature.

**Comment by chriskemp** [comment]
I previously looked through the closed issues before I resorted to the code to identify my problem! You reference reddit etc in some posts so I'm not sure I'll have found all of those.

My understanding of the code is that if the user turns it off via notification command, it will _never_ turn back on again through a zone or bluetooth change because highAccuracyModeSetting has been turned off.  Maybe I'm missing something but I can't see how that happens and it doens't seem to in practice - if it is as you say, then it'd already be covering my use case!

I think my simplest suggestion is:

turn_on:
- turn on highAccuracyModeSetting
- set the force_on flag and clear a new force_off flag

turn_off: 
- if highAccuracyModeSetting is on but there are constraints set then clear the force_on flag and set the force_off flag
- if highAccuracyModeSetting is on but there are no contraints set, then turn off the setting (and clear the force flags)

If highAccuracyModeSetting is on and there are constraints set, then clear the force_on flag if a constraint would be turning it on anyway.
If highAccuracyModeSetting is on and there are constraints set, then clear the force_off flag if no constraint would be turning it on anyway.

I think that provides a clear override.  In the case of no constraints (zones/bluetooth) it simply turns everything on or off.  If there are constraints set up then turn_on forces it on until turn_off or a constraint _deactivates_ (if currently clear it'd have to set and then clear, otherwise just clear).  Turn_off forces it off until turn_on or a constraint _activates_ (if currenly set, it'd have to clear and then set, otherwise just set).

Currently the behaviour isn't symmetric and to me that's strange.

I'll happily code that if you agree?

**Comment by dshokouhi** [comment]
> My understanding of the code is that if the user turns it off via notification command, it will _never_ turn back on again through a zone or bluetooth change because highAccuracyModeSetting has been turned off. Maybe I'm missing something but I can't see how that happens and it doesn't seem to in practice - if it is as you say, then it'd already be covering my use case!

So the constraints should be turning off the forcing of high accuracy mode here just above your modifications:
https://github.com/home-assistant/android/blob/dab3640c6b80d273c92ebda708b658f1b9bb0674/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L391-L395

This all gets re-evaluated during `setupBackgroundLocation()` which gets called quite frequently as its also part of our SensorWorker which runs on boot and ensures the services are running properly.

What exact issue are you hitting? Are you using zone or BT constraints? This file admittedly can get a bit daunting with the architecture of the app which is part of the reason why we have so much logging in place so users can make some sense of it.

> I'll happily code that if you agree?

If we were to go down the path of adding a new override flag then maybe its best to put that in the hands of the user in the notification command. That would at least allow things to remain as is and for users who need that additional adjustment they can use that too.

**Comment by chriskemp** [comment]
The issue I have is that the code you reference isn't executed if the highAccuracyModeSetting is off:

https://github.com/home-assistant/android/blob/dab3640c6b80d273c92ebda708b658f1b9bb0674/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L385-L387

The highAccuracyModeSetting is turned off (not "overridden") by a turn_off intent:

https://github.com/home-assistant/android/blob/dab3640c6b80d273c92ebda708b658f1b9bb0674/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L190

or notifcation command (which then calls the intent anyway):

https://github.com/home-assistant/android/blob/dab3640c6b80d273c92ebda708b658f1b9bb0674/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L809-L810 

So whatever use case, if you issue turn_off, it's off until you send turn_on.  Whereas if you issue turn_on, it's on until you issue turn_off _or_ you go into and out of a constraint.

The use case that isn't working is a zone around home.
- normal use all fine
- away from home I issue turn_on and get high accuracy.  If I leave it on that's fine it'll turn off when I next go through the zone.
- but if I turn it off again with turn_off before I get home, it's no just plain off and won't turn on again when I go into the zone.

Another use case that doesn't work is the exact one you first mentioned:
>  if high accuracy was turned on because a BT device got connected, then if a user forces it off via notification command it should not turn back on until the next time it triggers.

...if a user forces it off via notification command it will _not_ turn back on when it next triggers.  If it did, then I'd be happy as it'd turn back on when I next got home.  It doesn't because the turn_off has set highAccuracyModeSetting to off.  The code you reference also doesn't really apply in either your or my case because it clears forceHighAccuracyModeOn which would have already been cleared by the turn_off:

https://github.com/home-assistant/android/blob/dab3640c6b80d273c92ebda708b658f1b9bb0674/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L189

Sorry this is long winded....shall I send a PR of my suggestion which fixes it to behave as I think you want and you can see whay you think?

**Comment by dshokouhi** [comment]
Ok I see what you are saying but what you are proposing is a behavior change which will result in a breaking change for users who already have automations built around existing behavior. So I think whatever we do here we need to take into account that we should keep current behavior to not introduce a breaking change and add the new behavior in a new flag controlled by the user.

**Comment by chriskemp** [comment]
I've implemented force_on and force_off whilst leaving turn_on and turn_off as was.

I've tested all the combinations walking in and out of my home zone and it seems to do what I'm expecting.  Turn_on and turn_off shouldn't be changed by my code and as far as I can tell they function as they used to.

I've done a small doc change to explain:  [https://github.com/home-assistant/companion.home-assistant/pull/822](url)

HTH

**Comment by ludeeus** [comment]
The bot has a bug, it was supposed to post this:

---

Hello @chriskemp,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [f46244c](https://github.com/home-assistant/android/pull/2906/commits/f46244c3eceb0cc048a1c04a4ca7c65296d2bc6a) This commit has something that looks like an email address (chris@kemptechnology.co.uk). Maybe try linking that to GitHub?

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
        ```
        git commit --amend --author="Author Name <email@address.com>"
        ```
      (substituting "Author Name" and "`email@address.com`" for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by dshokouhi** [comment]
I _think_ there are still commits that are hitting the above error in this PR

**Comment by chriskemp** [comment]
Has that fixed it?  If not I can easily do a new branch with just the one correct commit - but change I change the PR to that....or just do a new PR?

**Comment by dshokouhi** [comment]
> Has that fixed it? If not I can easily do a new branch with just the one correct commit - but can I change the PR to that....or do I just have to do a new PR?

looks like its still not correct, I think you need to rewrite the history of commits in this branch to correct it. A new PR with a clean commit and branch will be good. Also its preferrable to use a different branch name than `master` when you submit a PR.

**Comment by homeassistant** [comment]
Hello @chriskemp,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:


- [`f46244c3eceb0cc048a1c04a4ca7c65296d2bc6a`](https://github.com/home-assistant/android/pull/2906/commits/f46244c3eceb0cc048a1c04a4ca7c65296d2bc6a) - This commit has something that looks like an email address (chris@kemptechnology.co.uk). Maybe try linking that to GitHub?.


- [`ab580f5611046cbbbfe9c5c3acf6f4c026168bae`](https://github.com/home-assistant/android/pull/2906/commits/ab580f5611046cbbbfe9c5c3acf6f4c026168bae) - This commit has something that looks like an email address (chris@kemptechnology.co.uk). Maybe try linking that to GitHub?.


Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting "Author Name" and "`email@address.com`" for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Pull request closed without merging**
