### PR TITLE
Improve monochrome icon

### PR DESCRIPTION
**Pull request by Dubzer**
## Summary
I noticed that the Home Assistant monochrome app icon looked weird compared to the others. So, I re-generated it with Android Studio to better match the guideline grid.

## Screenshots

before

after

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by Dubzer** [comment]
I'm not sure about the documentation. Is it required here?

**Comment by jpelgrom** [comment]
I agree it is good to better match other app's icon sizes, and it looks better in your screenshot, but it isn't working for me when building with the branch you supplied. The new drawables seem to be exactly the same as the existing foreground icon drawable?

Also does `ic_launcher_monochrome.xml` need to be duplicated?

> I'm not sure about the documentation. Is it required here?

No, a change to the documentation wouldn't be required for this PR.

**Comment by dshokouhi** [comment]
I think the debug app icon should still be different than the production app icon, if we keep them the same it will be hard to distinguish between the 2 when themed icons are used on the device.

**Comment by jpelgrom** [comment]
> I think the debug app icon should still be different than the production app icon

I think they're currently also the same when using themed icons? It seems to be limited to the home screen, so not impossible to tell them apart (still using the default color in the app drawer, overview, ...).

**Comment by Dubzer** [comment]
> The new drawables seem to be exactly the same as the existing foreground icon drawable?

This was not intended. Fixed!

Also, I removed debug version of the icon.

**Comment by jpelgrom** [comment]
Tested again and now the icon appears to match the screenshot.

@dshokouhi Do you feel like there should be a different monochrome icon for the debug builds? Not sure how to interpret your 👍 on my last comment.

**Comment by dshokouhi** [comment]
> @dshokouhi Do you feel like there should be a different monochrome icon for the debug builds? Not sure how to interpret your 👍 on my last comment.

My 👍 was in response to the icon already being used. I didn't realize that. Also you are correct that they will still be distinguishable there.

**Review by jpelgrom — APPROVED** [review]

**Review by JBassett — APPROVED** [review]

**Pull request merged**
