### PR TITLE
Bump AGP, Gradle and Kotlin Versions

### PR DESCRIPTION
**Pull request by runningcode**
## Summary
This bumps [AGP](https://developer.android.com/studio/releases/gradle-plugin#4-2-0), [Gradle](https://docs.gradle.org/7.0.2/release-notes.html), [Kotlin](https://blog.jetbrains.com/kotlin/2021/05/kotlin-1-5-0-released/), [Ktlint](https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v10.0.0).
The changes to file formatting are caused by an upgrade the the ktlint-gradle-plugin.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by dshokouhi** [comment]
hmm a lil surprised that `ktlint` didn't pick up on the imports no longer being in the correct order, did they finally fix that? I know Android Studio always liked to add `java*` after `kotlin*` so I always had to manually correct it to keep `ktlint` happy lol

**Comment by runningcode** [comment]
@dshokouhi, perhaps this change is related? https://github.com/pinterest/ktlint/issues/701
what would you like me to do here? Should I revert the ktlint changes and make a separate PR for that?

**Comment by dshokouhi** [comment]
@runningcode as long as `ktlint` doesn't complain I don't see any issues with it personally.  My comment was merely an observation based on how often I have to correct the file to satisfy `ktlint` because anytime android studio imports a java item it places it at the bottom instead of alphabetically.

**Comment by runningcode** [comment]
Oh, I think I misunderstood. Thanks for clarifying. All the code formatting in this PR was done with ktlint. I did not do any code formatting from Android Studio.

**Review by JBassett — APPROVED** [review]

**Pull request merged**
