### PR TITLE
Change default websocket behavior for google play store installations

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Based on feedback from users changing the full version to default to `never`

Updating the options to be more clear on what they actually mean

Updates the changelog for these 2 changes.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#688

### CODE REVIEW

**Review by JBassett — APPROVED** [review]

**Comment by jpelgrom** [comment]
Maybe you're already working on this, but there should be a documentation PR to update websocket mentions when they refer to Android settings

**Comment by dshokouhi** [comment]
> Maybe you're already working on this, but there should be a documentation PR to update websocket mentions when they refer to Android settings

good call, totally forgot lol

**Review by JBassett — APPROVED** [review]

**Comment by dnestico** [comment]
Ok I just have a question and I have it set to only show it when I'm "On home WiFi" but when that's selected it disappears so I have to set it too "always" instead.

How can this be fixed?, Since I want the option where it only shows it when I'm at home.  #67706

**Comment by dshokouhi** [comment]
> Ok I just have a question and I have it set to only show it when I'm "On home WiFi" but when that's selected it disappears so I have to set it too "always" instead.
> 
> How can this be fixed?, Since I want the option where it only shows it when I'm at home.  
> 
> https://github.com/home-assistant/core/issues/67706#issue-1160425222

Please don't comment on old merged PRs. If you feel you have an issue with the app please create a new issue and make sure to fill out the issue template completely including the logs.

**Comment by dnestico** [comment]
I did create an issue and I linked it in the question.

**Comment by dshokouhi** [comment]
That is not filed in the correct repo. Close that one and open a new one here please.

**Pull request merged**
