### PR TITLE
Add signal strength and data network type sensors

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Fixes: #4572 by adding 4 new sensors for signal strength and data network type for each SIM slot

## Screenshots

image

image

image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#1094

### CODE REVIEW

**Comment by jpelgrom** [comment]
Should/can these by split up for SIM 1 and 2?

**Comment by dshokouhi** [comment]
may not be simple for me to test as I only use one. FWIW my phone reports its using SIM2 but still reports data. I assume the first option in the list is probably the active SIM card?

**Comment by jpelgrom** [comment]
I think only one can be active for data at a time, but both can have signal strength and be active in standby (you can receive a call on either SIM).

**Comment by dshokouhi** [comment]
thats a good point, unfortunately the API seems to only give a list of entries but none of them have anything to help identify which operator it belongs to. The API even states teh order of the list items may not always be the same so we cant assume SIM indexes either. 🤔 My own personal assumption is whichever was most recently actively used is probably first?

**Comment by jpelgrom** [comment]
So after testing this we should definitely split this up, it seems to handle two sims but it's confusing from which one the data is coming. @dshokouhi as discussed in DMs I've pushed changes to your branch because you're unable to test this yourself and describing here while I could push is pointless, so please review 🤝

Additionally, for the data network type sensor branding is an issue 😅 as 4G+/LTE Advanced and some 5G networks still show as LTE because they technically are ([display info overrides](https://developer.android.com/about/versions/11/features/5g#detection)). We should add a note to the docs.

**Comment by jpelgrom** [comment]
Updated sensor list: 
List of app sensors, titled 'Phone sensors' with new options for 'Data network type (SIM 1)', 'Data network type (SIM 2)', 'Signal strength (SIM 1)', 'Signal strength (SIM 2)'

**Comment by dshokouhi** [comment]
this works great on my end! Thank you for fixing it!!!

image

**Review by jpelgrom — APPROVED** [review]
No more comments from me, feel free to merge if you're happy as well

**Pull request merged**
